### ISSUE TITLE
Header color pallets not fully appearing

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/tourbi#2]
The color pallets in the header section will not fully appear for the following options :
 Dropdown background color: https://prnt.sc/uuots2
Dropdown menu color: https://prnt.sc/uuotzx
Dropdown menu hover color: https://prnt.sc/uuou4u

**Comment by codepixar** [comment]
Thanks @Florin415 for your query. As we are using the 'Epsilon Framework' & 'Epsilon Dashboard' library with each of our wp themes, the customizer color options and theme options are coming from there. We are just using their library with our theme. So, the bug is coming from there. So, they should update the issue by their end.

Thanks
